name: 1.0.0$(Rev:.r)
resources:
  repositories:
  - repository: github-demo
    type: github
    name: davorzuti88/github-demo
    endpoint: github.com_davorzuti88
    ref: main
    trigger:
      branches:
        include:
        - refs/heads/main
variables:
- name: name
  value: Davor
pool:
  name: default
stages:
- stage: __default
  jobs:
  - job: checkout
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      inputs:
        repository: test_toni
  - job: helloworld
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "Hello, $(name)"

